### ISSUE TITLE
Research appropiate technologies to use in the project

### ISSUE THREAD

**Issue by garciafdezpatricia** [Arquisoft/lomap_en2a#9]
Search appropiate technologies to implement the project: advantages and disadvantages

**Comment by UO283216** [comment]
I have been taking a look at different technologies for us to host the application once developed and we should take into account some of the ones in [https://www.codeinwp.com/blog/best-nodejs-hosting](this page). I think it is pretty interesting to consider also Azure with a little resource machine to host the application since we have some credit left. Another option I saw that is pretty interesting is [https://www.heroku.com/](Heroku)(mentioned in the top10) that offers a plan that only costs 5$ a month and since we are 4 people for 4$ each we solve the problem of the hosting platform (take a look at advantages and disadvantages).

**Comment by UO283216** [comment]
Taking into account that we have decided to use google maps api it may be interesting to personalice the view of the map, i've found something that could  be usefull for doing so. 
https://mapstyle.withgoogle.com/

**Comment by SantiFC12** [comment]
We can take a look to this, to make working in React easier: https://react-redux.js.org/

**Comment by UO283216** [comment]
It may be interesting to use this library to represent the map location for now. It can be interesting to still try to mantain the Adapter pattern.
https://medium.com/@allynak/how-to-use-google-map-api-in-react-app-edb59f64ac9d
