### ISSUE TITLE
Category mandatory?

### ISSUE THREAD

**Issue by garciafdezpatricia** [Arquisoft/lomap_en2a#98]
We have to choose if the category of a location is mandatory or not (to fix bugs in the code)

**Comment by UO283216** [comment]
I would make so that if no category is selected the 'other' category is selected. If u want to select a category it should be one of the predifined ones (at least by now) so if no category fits the location the 'other' category is selected. For now it can be like a 'cajon desastre' for locations that do not have a category.

**Comment by garciafdezpatricia** [comment]
Okei, will implement it and commit it :) before 18.00h if possible :)

**Comment by garciafdezpatricia** [comment]
Took shorter than I thought 🤣. Check if it is working for you now and if it is, I think it is done!

**Comment by UO283216** [comment]
It worksssss
